export const agentSeeds = [
  {
    title: "Technical Support Agent",
    areaOfExpertise: [
      { expertise: "Troubleshooting", experience: 4 },
      { expertise: "Remote desktop support", experience: 3 },
    ],
    about: "Resolves technical issues promptly to minimize downtime.",
    qualification: [{ qualification: "CompTIA A+", year: 2 }],
    education: [{ education: "Diploma in IT Support", year: 3 }],
    user: "14",
    isActive: true,
    rating: 4.5,
    languages: ["English", "Kinyarwanda"],
  },
  {
    title: "Call Center Representative",
    areaOfExpertise: [
      { expertise: "Inbound call handling", experience: 5 },
      { expertise: "Customer data entry", experience: 3 },
    ],
    about: "First point of contact for customer queries and updates.",
    qualification: [{ qualification: "Call Handling Certification", year: 3 }],
    education: [{ education: "Certificate in Communication Skills", year: 3 }],
    user: "13",
    isActive: true,
    rating: 4.7,
    languages: ["English", "Kinyarwanda", "French"],
  },
  {
    title: "Field Service Agent",
    areaOfExpertise: [
      { expertise: "On-site installation", experience: 4 },
      { expertise: "Hardware replacement", experience: 2 },
    ],
    about: "Performs field duties ensuring services run smoothly offsite.",
    qualification: [{ qualification: "Field Operations Training", year: 3 }],
    education: [
      { education: "Technical Certification in Field Services", year: 3 },
    ],
    user: "12",
    isActive: true,
    rating: 4.6,
    languages: ["English", "Kinyarwanda"],
  },
  {
    title: "Customer Success Associate",
    areaOfExpertise: [
      { expertise: "Customer retention", experience: 3 },
      { expertise: "Onboarding support", experience: 2 },
    ],
    about:
      "Builds long-term relationships with clients through support and care.",
    qualification: [{ qualification: "Customer Success Foundations", year: 2 }],
    education: [{ education: "Diploma in Customer Experience", year: 3 }],
    user: "15",
    isActive: true,
    rating: 4.8,
    languages: ["Kinyarwanda", "English"],
  },
  {
    title: "Escalation Specialist",
    areaOfExpertise: [
      { expertise: "Issue resolution", experience: 5 },
      { expertise: "Interdepartmental communication", experience: 4 },
    ],
    about: "Handles complex cases and escalations with efficiency.",
    qualification: [{ qualification: "Conflict Resolution Training", year: 4 }],
    education: [{ education: "B.A. in Public Relations", year: 4 }],
    user: "18",
    isActive: true,
    rating: 4.9,
    languages: ["English", "French", "Kinyarwanda"],
  },
  {
    title: "Sales Representative",
    areaOfExpertise: [
      { expertise: "Outbound calls", experience: 4 },
      { expertise: "CRM management", experience: 3 },
    ],
    about: "Drives business growth by converting leads into customers.",
    qualification: [{ qualification: "Salesforce CRM Training", year: 3 }],
    education: [{ education: "Diploma in Sales and Marketing", year: 3 }],
    user: "16",
    isActive: true,
    rating: 4.3,
    languages: ["English", "Swahili"],
  },
  {
    title: "Billing Support Officer",
    areaOfExpertise: [
      { expertise: "Invoice processing", experience: 3 },
      { expertise: "Subscription management", experience: 2 },
    ],
    about: "Ensures billing issues are handled with accuracy and clarity.",
    qualification: [{ qualification: "Finance Software Training", year: 2 }],
    education: [{ education: "Diploma in Accounting", year: 3 }],
    user: "11",
    isActive: true,
    rating: 4.4,
    languages: ["English", "Kinyarwanda"],
  },
  {
    title: "IT Helpdesk Technician",
    areaOfExpertise: [
      { expertise: "Password resets", experience: 4 },
      { expertise: "VPN support", experience: 3 },
    ],
    about: "Provides IT assistance and keeps systems operational for staff.",
    qualification: [{ qualification: "ITIL Foundation", year: 2 }],
    education: [{ education: "Diploma in Information Technology", year: 3 }],
    user: "17",
    isActive: true,
    rating: 4.6,
    languages: ["English"],
  },
  {
    title: "Network Support Engineer",
    areaOfExpertise: [
      { expertise: "LAN/WAN troubleshooting", experience: 5 },
      { expertise: "Firewall configuration", experience: 4 },
    ],
    about: "Manages and supports secure and efficient network operations.",
    qualification: [{ qualification: "CCNA", year: 3 }],
    education: [{ education: "B.Sc. in Network Engineering", year: 4 }],
    user: "10",
    isActive: true,
    rating: 4.7,
    languages: ["English"],
  },
  {
    title: "Dispatch Coordinator",
    areaOfExpertise: [
      { expertise: "Route optimization", experience: 4 },
      { expertise: "Field team coordination", experience: 3 },
    ],
    about: "Manages scheduling and deployment of field personnel.",
    qualification: [{ qualification: "Dispatch Training Program", year: 3 }],
    education: [{ education: "Diploma in Logistics", year: 3 }],
    user: "2",
    isActive: true,
    rating: 4.5,
    languages: ["English", "Swahili", "Kinyarwanda"],
  },
  {
    title: "Call Quality Analyst",
    areaOfExpertise: [
      { expertise: "Call monitoring", experience: 4 },
      { expertise: "Agent feedback & coaching", experience: 3 },
    ],
    about:
      "Ensures calls meet quality standards and improves agent performance.",
    qualification: [
      { qualification: "Quality Assurance Certification", year: 3 },
    ],
    education: [{ education: "Diploma in Business Communication", year: 3 }],
    user: "3",
    isActive: true,
    rating: 4.6,
    languages: ["English", "Kinyarwanda"],
  },
];
